### PR TITLE
Added support for Objective-C in Logger protocol.

### PR DESCRIPTION
**Pull request by newboadki**

### CODE REVIEW

**Comment by vilanovi** [comment]
@newboadki which is the status of this?

**Comment by newboadki** [comment]
@vilanovi, There is a comment in the analogous pull request for the Harmony-reference repository. 
I will address it.

**Comment by vilanovi** [comment]
Btw, you added "HM" as prefix. Until now, everything is listed as "MJ", but might be worthy to change all to "HM". However, if we think this is too time consuming, mayb we could leave it as "MJ" to keep consistent with existing stuff.

What do you think is best?

**Comment by newboadki** [comment]
I think we should change everything to use HM. Do we all agree on HM? If so, I'll go ahead.

**Comment by RubenVot** [comment]
@vilanovi @newboadki  Do you mean to rename all the classes in the project? This will force all the projects using those classes to refactor :(  

 If NSString was never renamed to APString I think we can keep MJ for the future generations :D

**Comment by newboadki** [comment]
@RubenVot. You're right. Will change this pr to use MJ.

**Comment by vilanovi** [comment]
Yes, I also was thinking in retrocompatibility. If this was Swift, I would have voted to update everything, as branding is important. In case of Obj-C, we don't really care that much, as this is not going to be used that much. 

I'm ok to keep MJ :).

**Comment by newboadki** [comment]
Done.

**Comment by newboadki** [comment]
@vilanovi, can we merge this? (And its counterpart in the reference repo)

**Comment by vilanovi** [comment]
Rules for merge: you must have at least 2 approved reviews. Assign the review to me/jose/ruben/paolo and we will reveiw it :)

**Review by vilanovi — APPROVED** [review]

**Review by joselufo — APPROVED** [review]
all ok

**Review by RubenVot — APPROVED** [review]

**Comment by vilanovi** [comment]
@newboadki you can proceed and merge

**Pull request merged**
