### PR TITLE
Added Logger protocol and DeviceConsoleLogger concrete implementation.

### PR DESCRIPTION
**Pull request by newboadki**
Implementation of a Logger protocol. https://github.com/mobilejazz/harmony-reference/pull/5

### CODE REVIEW

**Comment by RubenVot** [comment]
Hi @newboadki , de implementation looks good. A few comments:

 If I understood correctly the output in the console will be (for example): 
```
whateverLoggerInstance.print("UIModule", "the button was pressed")
$Warning - UIModule - { the button was pressed } 
```
I think the brackets might become a bit messy when we have many logs in the console.
I would recommend something like *LogLevel[tag1, tag2, tag3]: the log message*
```
$Warning[UIModule, LoginScreen]: the button was pressed
```

Feature request (for the future): 
1. Array of tags
2. Log level configurable. (only errors, or warning and errors) 
3. Verbose log level

**Review by RubenVot — APPROVED** [review]

**Comment by RubenVot** [comment]
(Approving as my comments are opportunity for improvement but not blockers)

**Review by joselufo — APPROVED** [review]
Looks Ok for me.

**Review by vilanovi — APPROVED** [review]

**Comment by newboadki** [comment]
Ok @RubenVot, I'll change the format to remove the brackets.

**Comment by newboadki** [comment]
Changed format @RubenVot.

**Review by RubenVot — APPROVED** [review]

**Review by vilanovi — APPROVED** [review]

**Pull request merged**
