### PR TITLE
Renaming NetworkStorageRepository to FastSlowRepository

### PR DESCRIPTION
**Pull request by vilanovi**
- Updated `NetworkStorageRepository` for `FastSlowRepository`
- Updated any references to `network` for `slow`
- Updated any references to `storage` for `fast`

### CODE REVIEW

**Comment by RubenVot** [comment]
I guess this change comes after a discussion and it has a good reason for it. But I don't really understand the purpose of renaming NetworkStorage to FastSlow. 
Without more context it looks a bit like comparing bacon and speed 🤔
I guess that Fast Slow may reference something fast cached and something slower as second option. If this is the point I would expect something like Master-Slave or Primary-Secondary

**Comment by vilanovi** [comment]
@RubenVot, you're right. Sorry for not providing more context.

The idea behind is to remove the connotation that the "NetworkStorageRepository" only does "network" and "storage". It is actually a generic implementation of a repository that contains two data sources and operates them depending on the operation used.

My initial proposal was to call them "Fast" and "Slow", just to give names. "Master-Slave" or "Primary-Secondary" also work. 

Note the idea of "Fast-Slow" come from a perspective where you would use this repository to choose between a "fast-access data source" or a more "slow-access data source", thinking for example of a network (slow) and storage (fast) or a relational-database (slow) fast key-value caching system (fast).

Also, we had a motivation to move away from network-storage naming as we want to present this repository in the MJ University to the web team, and we need to rename it to something more "generic" as they don't need this specific scenario.

**Review by joselufo — COMMENTED** [review]
I don't really like **Fast** & **Slow** naming because it's not really what it's doing the Repository. 

Regarding the **Master** & **Slave** naming, these connotations are more related to replication and high availability than caching. 

_So, what should be a good name?_ 
I don't really know but for me at least the Repository name should be called "CacheRepository" as it's basically caching and nothing more because if you read the code, it's only handling the ObjectNotFound and InvalidObject errors to determinate what to do. 

The problem is with the **Operations** names because we can have **CacheOperation** and **CacheSycnOperation** but I don't know the naming for the other two operations.

**Comment by vilanovi** [comment]
If we go for a `CacheRepository` then, we could use the names of `main` for the main data source and `cache` for the cache-based data source.

The operations could be labeled:

1. `MainOperation`: Use only the main data source and do not cache anything
2. `MainSyncOperation`: Use the main data source and cache the result
3. `CacheOperation`: Use the cache only
4. `CacheSyncOperation`: Use the cache first, otherwise use the main data source.

I like the overall naming. Stuff would be like this:

```
let repository = CacheRepository(main: networkDataSource, cache: storageDataSource)

// Fetch from cache first, otherwise network. Typical behavior of a network-based with cache app.
repository.get("myUser", operation: CacheSyncOperation())

// Fetch from network first, then cache. Typicial behavior of a pull-to-refresh.
repository.get("myUser", operation: MainSyncOperation())

// Fetch from cache only
repository.get("myUser", operation: CacheOperation())

// Fetch from main only, don't invovle cache
repository.get("myUser", operation: MainOperation())
```

What do you think?

**Comment by joselufo** [comment]
@vilanovi I like the naming that you proposed **Main** and having it as a **CacheRepository** is more explanatory what it does. 

Let's see what the team say.

**Comment by RubenVot** [comment]
Great!
Main/Cache makes a lot of sense.

**Review by RubenVot — APPROVED** [review]

**Comment by vilanovi** [comment]
Updated the mjcore-reference as well (Kotlin examples must be updated yet).

**Pull request merged**
